# Generated by Django 6.0.4 on 2026-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_filr',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
