# Generated by Django 6.0.4 on 2026-05-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_pdf_filr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pdf_filr',
            new_name='pdf_file',
        ),
    ]
